2025-05-14 13:45:56,192 - ERROR - Connection error: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: /dbc-df998298-4c7e.cloud.databricks.com.cloud.databricks.com/api/2.0/fs/files/Volumes/amperity_marketplace/bronze/chuck/stitch-2025-05-14_13-45.json?overwrite=true (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x104cb5f90>: Failed to resolve 'https' ([Errno 8] nodename nor servname provided, or not known)"))
2025-05-14 13:45:56,193 - ERROR - Stitch setup error: name 'scan_result_data' is not defined
